// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type FoodRegistry struct {
	ProductID              int32
	Name                   string
	Gtin                   sql.NullString
	Category               sql.NullString
	Description            sql.NullString
	UnitType               string
	Quantity               sql.NullInt32
	PortionCount           sql.NullInt32
	ExpirationAfterOpening sql.NullInt32
	NutrientsPerItem       sql.NullBool
	Calories               sql.NullString
	Fats                   sql.NullString
	Saturated              sql.NullString
	Carbs                  sql.NullString
	Sugars                 sql.NullString
	Protein                sql.NullString
	Fiber                  sql.NullString
	Sodium                 sql.NullString
	CreatedAt              sql.NullTime
	UpdatedAt              sql.NullTime
	CreatedBy              uuid.NullUUID
	UodatedBy              uuid.NullUUID
}

type Inventory struct {
	ID                     int32
	UserID                 uuid.NullUUID
	ProductID              sql.NullInt32
	ExpirationDate         sql.NullTime
	ExpirationAfterOpening sql.NullInt32
	IsOpened               sql.NullBool
	MaxQuantity            float64
	CurrQuantity           float64
	PurchaseDate           sql.NullTime
	OpenedDate             sql.NullTime
	CreatedAt              sql.NullTime
	UpdatedAt              sql.NullTime
}

type Recipe struct {
	ID                  int32
	UserID              uuid.NullUUID
	Name                string
	Private             sql.NullBool
	Description         sql.NullString
	Instructions        sql.NullString
	UnitType            string
	Quantity            sql.NullInt32
	NutrientsPerPortion sql.NullBool
	Calories            sql.NullString
	Fats                sql.NullString
	Saturated           sql.NullString
	Carbs               sql.NullString
	Sugars              sql.NullString
	Protein             sql.NullString
	Fiber               sql.NullString
	Sodium              sql.NullString
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
}

type RecipeIngredient struct {
	ID        int32
	RecipeID  sql.NullInt32
	ProductID sql.NullInt32
	Quantity  float64
}

type User struct {
	ID            uuid.UUID
	Username      string
	Email         string
	PasswordHash  string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	LastLogin     sql.NullTime
	ActiveAccount sql.NullBool
}
