package rt

import (
	"context"
	"time"

	"github.com/Laelapa/PlateOps/internal/repository"
	"github.com/Laelapa/PlateOps/util/typeconvert"

	"github.com/Laelapa/GoHome/logging"
	"github.com/google/uuid"
	"go.uber.org/zap"
)

type Params struct {
	userID    uuid.UUID
	token     string
	expiresAt time.Time
	userAgent string
	ipAddress string
}

// RegisterNewToken registers a new refresh token with the database.
// It exists in large part to abstract away the type conversions that must be done to accommodate the repository functions.
// It takes the token parameters as a struct, converts them to the appropriate pgtypes for the repository layer,
// and then passes them along to the repository functions.
//
// It takes a context, a logger, and the token parameters that are to be saved.
// It propagates any errors generated by the repository layer.
// It, also, generates a log message with the token or error information.
func RegisterNewToken(queries *repository.Queries, logger *logging.Logger, params Params) error {

	rParams := repository.CreateRefreshTokenParams{
		Token:     params.token,
		UserID:    typeconvert.GoogleUUIDToPgtypeUUID(params.userID),
		ExpiresAt: typeconvert.TimeToPgtypeTimestamp(params.expiresAt),
		UserAgent: params.userAgent,
		IpAddress: params.ipAddress,
	}

	rt, err := queries.CreateRefreshToken(context.Background(), rParams)
	if err != nil {
		logger.LogAppError(
			"Repository error registering refresh token",
			err,
			zap.String("token", params.token),
		)
		return err
	}
	logger.LogAppInfo(
		"Registered new refresh token",
		zap.String("token", rt.Token),
		zap.String("user_id", typeconvert.PgtypeUUIDToString(rt.UserID)),
		zap.Time("expires_at", rt.ExpiresAt.Time),
		zap.String("user_agent", rt.UserAgent),
		zap.String("ip_address", rt.IpAddress),
	)
	return nil
}
