// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: food_registry.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFoodEntry = `-- name: CreateFoodEntry :one
INSERT INTO food_registry (
    name, 
    GTIN, 
    category, 
    description, 
    unit_type, 
    quantity,
    portion_count,
    expiration_after_opening,
    nutrients_per_item,
    calories,
    fats,
    saturated,
    carbs,
    sugars,
    protein,
    fiber,
    sodium,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING product_id, name, gtin, category, description, unit_type, quantity, portion_count, expiration_after_opening, nutrients_per_item, calories, fats, saturated, carbs, sugars, protein, fiber, sodium, created_at, updated_at, created_by, updated_by
`

type CreateFoodEntryParams struct {
	Name                   pgtype.Text   `json:"name"`
	Gtin                   pgtype.Text   `json:"gtin"`
	Category               pgtype.Text   `json:"category"`
	Description            pgtype.Text   `json:"description"`
	UnitType               pgtype.Text   `json:"unit_type"`
	Quantity               pgtype.Int4   `json:"quantity"`
	PortionCount           pgtype.Int4   `json:"portion_count"`
	ExpirationAfterOpening pgtype.Int4   `json:"expiration_after_opening"`
	NutrientsPerItem       pgtype.Bool   `json:"nutrients_per_item"`
	Calories               pgtype.Float4 `json:"calories"`
	Fats                   pgtype.Float4 `json:"fats"`
	Saturated              pgtype.Float4 `json:"saturated"`
	Carbs                  pgtype.Float4 `json:"carbs"`
	Sugars                 pgtype.Float4 `json:"sugars"`
	Protein                pgtype.Float4 `json:"protein"`
	Fiber                  pgtype.Float4 `json:"fiber"`
	Sodium                 pgtype.Float4 `json:"sodium"`
	CreatedBy              pgtype.UUID   `json:"created_by"`
}

func (q *Queries) CreateFoodEntry(ctx context.Context, arg CreateFoodEntryParams) (FoodRegistry, error) {
	row := q.db.QueryRow(ctx, createFoodEntry,
		arg.Name,
		arg.Gtin,
		arg.Category,
		arg.Description,
		arg.UnitType,
		arg.Quantity,
		arg.PortionCount,
		arg.ExpirationAfterOpening,
		arg.NutrientsPerItem,
		arg.Calories,
		arg.Fats,
		arg.Saturated,
		arg.Carbs,
		arg.Sugars,
		arg.Protein,
		arg.Fiber,
		arg.Sodium,
		arg.CreatedBy,
	)
	var i FoodRegistry
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Gtin,
		&i.Category,
		&i.Description,
		&i.UnitType,
		&i.Quantity,
		&i.PortionCount,
		&i.ExpirationAfterOpening,
		&i.NutrientsPerItem,
		&i.Calories,
		&i.Fats,
		&i.Saturated,
		&i.Carbs,
		&i.Sugars,
		&i.Protein,
		&i.Fiber,
		&i.Sodium,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteFoodEntry = `-- name: DeleteFoodEntry :exec
DELETE FROM food_registry
WHERE product_id = $1
`

func (q *Queries) DeleteFoodEntry(ctx context.Context, productID int32) error {
	_, err := q.db.Exec(ctx, deleteFoodEntry, productID)
	return err
}

const getFoodEntriesByCategory = `-- name: GetFoodEntriesByCategory :many
SELECT product_id, name, gtin, category, description, unit_type, quantity, portion_count, expiration_after_opening, nutrients_per_item, calories, fats, saturated, carbs, sugars, protein, fiber, sodium, created_at, updated_at, created_by, updated_by
FROM food_registry
WHERE category = $1
`

func (q *Queries) GetFoodEntriesByCategory(ctx context.Context, category pgtype.Text) ([]FoodRegistry, error) {
	rows, err := q.db.Query(ctx, getFoodEntriesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FoodRegistry
	for rows.Next() {
		var i FoodRegistry
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Gtin,
			&i.Category,
			&i.Description,
			&i.UnitType,
			&i.Quantity,
			&i.PortionCount,
			&i.ExpirationAfterOpening,
			&i.NutrientsPerItem,
			&i.Calories,
			&i.Fats,
			&i.Saturated,
			&i.Carbs,
			&i.Sugars,
			&i.Protein,
			&i.Fiber,
			&i.Sodium,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodEntriesByNameContains = `-- name: GetFoodEntriesByNameContains :many
SELECT product_id, name, gtin, category, description, unit_type, quantity, portion_count, expiration_after_opening, nutrients_per_item, calories, fats, saturated, carbs, sugars, protein, fiber, sodium, created_at, updated_at, created_by, updated_by
FROM food_registry
WHERE LOWER(name) LIKE LOWER('%' || $1 || '%')
OR similarity(LOWER(name), LOWER($1)) > 0.4
ORDER BY similarity(LOWER(name), LOWER($1)) DESC, LENGTH(name), name
LIMIT 50
`

func (q *Queries) GetFoodEntriesByNameContains(ctx context.Context, dollar_1 pgtype.Text) ([]FoodRegistry, error) {
	rows, err := q.db.Query(ctx, getFoodEntriesByNameContains, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FoodRegistry
	for rows.Next() {
		var i FoodRegistry
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Gtin,
			&i.Category,
			&i.Description,
			&i.UnitType,
			&i.Quantity,
			&i.PortionCount,
			&i.ExpirationAfterOpening,
			&i.NutrientsPerItem,
			&i.Calories,
			&i.Fats,
			&i.Saturated,
			&i.Carbs,
			&i.Sugars,
			&i.Protein,
			&i.Fiber,
			&i.Sodium,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodEntryByGtin = `-- name: GetFoodEntryByGtin :one
SELECT product_id, name, gtin, category, description, unit_type, quantity, portion_count, expiration_after_opening, nutrients_per_item, calories, fats, saturated, carbs, sugars, protein, fiber, sodium, created_at, updated_at, created_by, updated_by
FROM food_registry
WHERE GTIN = $1
`

func (q *Queries) GetFoodEntryByGtin(ctx context.Context, gtin pgtype.Text) (FoodRegistry, error) {
	row := q.db.QueryRow(ctx, getFoodEntryByGtin, gtin)
	var i FoodRegistry
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Gtin,
		&i.Category,
		&i.Description,
		&i.UnitType,
		&i.Quantity,
		&i.PortionCount,
		&i.ExpirationAfterOpening,
		&i.NutrientsPerItem,
		&i.Calories,
		&i.Fats,
		&i.Saturated,
		&i.Carbs,
		&i.Sugars,
		&i.Protein,
		&i.Fiber,
		&i.Sodium,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getFoodEntryById = `-- name: GetFoodEntryById :one
SELECT product_id, name, gtin, category, description, unit_type, quantity, portion_count, expiration_after_opening, nutrients_per_item, calories, fats, saturated, carbs, sugars, protein, fiber, sodium, created_at, updated_at, created_by, updated_by
FROM food_registry
WHERE product_id = $1
`

func (q *Queries) GetFoodEntryById(ctx context.Context, productID int32) (FoodRegistry, error) {
	row := q.db.QueryRow(ctx, getFoodEntryById, productID)
	var i FoodRegistry
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Gtin,
		&i.Category,
		&i.Description,
		&i.UnitType,
		&i.Quantity,
		&i.PortionCount,
		&i.ExpirationAfterOpening,
		&i.NutrientsPerItem,
		&i.Calories,
		&i.Fats,
		&i.Saturated,
		&i.Carbs,
		&i.Sugars,
		&i.Protein,
		&i.Fiber,
		&i.Sodium,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateFoodEntry = `-- name: UpdateFoodEntry :exec
UPDATE food_registry
SET
    name = COALESCE($2, name),
    GTIN = COALESCE($3, GTIN),
    category = COALESCE($4, category),
    description = COALESCE($5, description),
    unit_type = COALESCE($6, unit_type),
    quantity = COALESCE($7, quantity),
    portion_count = COALESCE($8, portion_count),
    expiration_after_opening = COALESCE($9, expiration_after_opening),
    nutrients_per_item = COALESCE($10, nutrients_per_item),
    calories = COALESCE($11, calories),
    fats = COALESCE($12, fats),
    saturated = COALESCE($13, saturated),
    carbs = COALESCE($14, carbs),
    sugars = COALESCE($15, sugars),
    protein = COALESCE($16, protein),
    fiber = COALESCE($17, fiber),
    sodium = COALESCE($18, sodium),
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $19
WHERE product_id = $1
`

type UpdateFoodEntryParams struct {
	ProductID              int32         `json:"product_id"`
	Name                   pgtype.Text   `json:"name"`
	Gtin                   pgtype.Text   `json:"gtin"`
	Category               pgtype.Text   `json:"category"`
	Description            pgtype.Text   `json:"description"`
	UnitType               pgtype.Text   `json:"unit_type"`
	Quantity               pgtype.Int4   `json:"quantity"`
	PortionCount           pgtype.Int4   `json:"portion_count"`
	ExpirationAfterOpening pgtype.Int4   `json:"expiration_after_opening"`
	NutrientsPerItem       pgtype.Bool   `json:"nutrients_per_item"`
	Calories               pgtype.Float4 `json:"calories"`
	Fats                   pgtype.Float4 `json:"fats"`
	Saturated              pgtype.Float4 `json:"saturated"`
	Carbs                  pgtype.Float4 `json:"carbs"`
	Sugars                 pgtype.Float4 `json:"sugars"`
	Protein                pgtype.Float4 `json:"protein"`
	Fiber                  pgtype.Float4 `json:"fiber"`
	Sodium                 pgtype.Float4 `json:"sodium"`
	UpdatedBy              pgtype.UUID   `json:"updated_by"`
}

func (q *Queries) UpdateFoodEntry(ctx context.Context, arg UpdateFoodEntryParams) error {
	_, err := q.db.Exec(ctx, updateFoodEntry,
		arg.ProductID,
		arg.Name,
		arg.Gtin,
		arg.Category,
		arg.Description,
		arg.UnitType,
		arg.Quantity,
		arg.PortionCount,
		arg.ExpirationAfterOpening,
		arg.NutrientsPerItem,
		arg.Calories,
		arg.Fats,
		arg.Saturated,
		arg.Carbs,
		arg.Sugars,
		arg.Protein,
		arg.Fiber,
		arg.Sodium,
		arg.UpdatedBy,
	)
	return err
}
